### ISSUE TITLE
Use jsonTOsql.js script

### ISSUE THREAD

**Issue by bobstar-fr** [tomy137/mcc_recipies_convert_toSQL#2]
Hello
When I run the script in a Node.js window, or PowerShell windows or Command Prompt Windows I always have an error at position 6.
I am not a Javascript specialist....
How did you run this script without error.
Thanks

**Comment by tomy137** [comment]
The 6th line load the data contains into your json file. What is the error message ?

Please be careful between Linux and Windows path maybe ? This script was develloped on Linux so assets/test_fausses_crepes_FR.json is OK. Maye with windows the syntax is different ?

**Comment by bobstar-fr** [comment]
Thank you, LINUX is certainly the reason why the script does not work for me, I'm under Windows 10.
I will create a bootable USB key under Linux and try again.
At the start (with win10) I was not in the right file and I had the error position 6.
Now in Win10 ... and in the right folder when I enter the line "node jsonTOsql.js assets / test_fausses_crepes_FR.json> file" nothing happens ...
Linux will probably be the solution

**Comment by tomy137** [comment]
Don't hesitate to test this manipulation : https://www.windowscentral.com/install-windows-subsystem-linux-windows-10

Is it worth it !

**Comment by bobstar-fr** [comment]
OK, thanks
I tried with WSL and the file "file" is well created
I also tried to create a bootable USB key with Ubuntu 20.04, and the file "file" is well created

**Comment by bobstar-fr** [comment]
tomy137 write : 
> Don't hesitate to test this manipulation : https://www.windowscentral.com/install-windows-subsystem-linux-windows-10
> Is it worth it !
 Hello
I tried with WSL and it also works the file 'file "is well created.

**Comment by bobstar-fr** [comment]
Hello
How do you import the new recipe named "file" into the "Recipes" file to make only 1 "Recipes" file. I tried with "DB browser sql" and unable to save the new "Recipes" file to export in the MCC.
