### ISSUE TITLE
Instability of the USB connection of the MCC on the PC

### ISSUE THREAD

**Issue by bobstar-fr** [tomy137/mcc_recipies_convert_toSQL#4]
Hello
I note an instability of the USB connection of the MCC on the PC.
The MCC disconnects from the PC quite often for no apparent reason.
Everything seems to be well installed, the TWRP recovery works well and I managed to transfer the Recipes file and the "recipe pictures" files to the PC (via MCC \sdcard folder) but I had to start the transfer several times because of nuisance USB disconnections.
Do you have any idea about this problem?

**Comment by tomy137** [comment]
Hello
The only time when I experienced similar situation was because the MCC seems to automatically turn stand-by. But it was after long time and didn't bother me. 

Maybe it's your wire that is not well plug or poor quality ?

I don't have other idea.

**Comment by bobstar-fr** [comment]
Hello
Thank you. I don't think my cable is defective. It is possible that putting the MCC to sleep cuts the USB connection but in my case I don't think so because it doesn't happen all the time at the same time.
If anyone has another idea ...

**Comment by bobstar-fr** [comment]
Hello
I found my error in /system/build.prop .... I added "persist.sys.usb.config = mtp, adb" instead "persist.sys.usb.config=mtp, adb"
These spaces have ruined everything!
Attention! ! ! Do not copy and paste from the English version of the Tutorial .... There are syntax errors ....

Now all is fine.

Thanks to abgagu for the info.
